name = "anki-workshop"

compatibility_date = ""
main = "src/index.ts"

[[d1_databases]]
binding = ""
database_name = ""
database_id = ""
# used for drizzle migration
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
bucket_name = ""
binding = ""
